In [3]:
import numpy as np
a=np.array([1,2,3,4,5])

In [ ]:
#Array do not create new array by slicing for saving memory
#it is just a view as shown below.

In [4]:
a

array([1, 2, 3, 4, 5])

In [7]:
b=a.copy()

In [8]:
b

array([1, 2, 3, 4, 5])

In [10]:
c=b[::2]

In [11]:
c

array([1, 3, 5])

In [12]:
c[:]=20

In [13]:
b

array([20,  2, 20,  4, 20])